# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 07:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateField(default=datetime.date.today, verbose_name='Date of Follow')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='release date')),
                ('ext_id', models.CharField(default='0', max_length=64, unique=True)),
                ('tagline', models.TextField(default='', verbose_name='Tagline')),
                ('image_url', models.CharField(default='', max_length=256)),
                ('num_of_reviews', models.IntegerField(default=0, verbose_name='Number of Reviews')),
                ('average_review_score', models.FloatField(default=0, verbose_name='Average Review Score')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Review Score')),
                ('review_text', models.TextField(default='', verbose_name='Review Text')),
                ('review_date', models.DateField(default=datetime.date.today, verbose_name='Review Date')),
                ('second_review', models.TextField(default='', verbose_name='Second Impressions')),
                ('second_rev_date', models.DateField(default=datetime.date.today, verbose_name='Second Impressions Date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviediary.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_reviews', models.IntegerField(default=0, verbose_name='Number of Reviews')),
                ('reset_token', models.CharField(default='', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviediary.Movie')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviediary.Reviewer')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviediary.Reviewer'),
        ),
        migrations.AddField(
            model_name='following',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='moviediary.Reviewer'),
        ),
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='moviediary.Reviewer'),
        ),
    ]
