# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bio',
            field=models.TextField(default='', verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='review',
            name='love_movie_text',
            field=models.TextField(default='', verbose_name='Reason'),
        ),
    ]
