# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateField(default=datetime.date.today, verbose_name='Date of Follow')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_id',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.TextField(default='', verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Review Date'),
        ),
        migrations.AddField(
            model_name='review',
            name='second_rev_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Second Impressions Date'),
        ),
        migrations.AddField(
            model_name='review',
            name='second_review',
            field=models.TextField(default='', verbose_name='Second Impressions'),
        ),
        migrations.AddField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='num_of_reviews',
            field=models.IntegerField(default=0, verbose_name='Number of Reviews'),
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='AAAA', max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(default='', verbose_name='Review Text'),
        ),
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='moviediary.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='moviediary.User'),
        ),
    ]
