# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0002_auto_20160316_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviediary.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviediary.User')),
            ],
        ),
    ]
