# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0002_auto_20160510_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_movies', to='moviediary.Movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_reviewers', to='moviediary.Reviewer'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_movies', to='moviediary.Movie'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_reviewers', to='moviediary.Reviewer'),
        ),
    ]
