# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ext_id',
            field=models.CharField(default='0', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
