# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0003_auto_20160510_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_headline',
            field=models.TextField(default='', verbose_name='Review Headline'),
        ),
        migrations.AddField(
            model_name='review',
            name='second_headline',
            field=models.TextField(default='', verbose_name='Second Headline'),
        ),
    ]
