# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0004_auto_20160320_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='followed',
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(default='', max_length=12),
        ),
    ]
