# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0004_auto_20160512_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='bio',
            field=models.TextField(default='', verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='favourite_genres',
            field=models.TextField(default='', verbose_name='Favourite Genres'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='love_movie_text',
            field=models.TextField(default='', verbose_name='Love Movies'),
        ),
    ]
