# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviediary', '0005_auto_20160610_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='review',
            name='love_movie_text',
        ),
    ]
